server:
  port: 80
#  ssl:
#    key-store: classpath:213955697120108.p12
#    key-store-password: a123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
  tomcat:
    uri-encoding: UTF-8
  address: 0.0.0.0
  display-name: znl
spring:
  mvc:
    throw-exception-if-no-handler-found: false
  jpa:
      properties:
          hibernate:
              enable_lazy_load_no_trans: true
              dialect: org.hibernate.dialect.MySQL5Dialect

      show-sql: true
      hibernate:
          ddl-auto:  update
      database:  MYSQL

  datasource:
#      url: jdbc:mysql://120.25.91.237:3306/znl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
      url: jdbc:mysql://localhost:3306/znl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
#      username: root
#      password: open123
      username:  root
      password:  hitwh

  thymeleaf:
      cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  redis:
    database: 4
    host: 201.201.201.173
    port: 6379
    timeout: 5000
    pool:
      max-active: 64
      max-idle: 8
      max-wait: -1
  freemarker:
    prefer-file-system-access:
logging:
  level: debug
  path: logs

management:
  add-application-context-header: false
enableAuth: false

#系统配置
sysconfig:
#正是环境中服务器的域名 必须添加白名单里
  runServerSchema: http://
  runServerHostName: fastweb.guotongshiyou.com


#微信配置
wechatconfig:
  sessionHost: https://api.weixin.qq.com/sns/oauth2/access_token
  appId: wx30d2a05655df7746
  secret: b13bd0576973d0b8850e8ca7384ea683
  grantType: authorization_code
  notifyUrl: http://suyj.ngrok.cc/pay/wxpaynotify

#通联配置
allinpay:
  syb_cusid: '242690089996452' #通联用户id
  syb_appid: '00007511' #通联应用id
  syb_appkey: transguotongsecret #t通联应用对应的key
  syb_apiurl: https://vsp.allinpay.com/apiweb/unitorder #请求的路径
  gatewayconsts: #网关支付的一些配置
    merchantid: '008500189990304'  #商户id
    merchantkey: 'fcc3c40d59c191b3e91f47a03c010900'
    url_unionregister: https://cashier.allinpay.com/usercenter/merchant/UserInfo/reg.do #通联用户注册地址
    url_ordersubmit: https://cashier.allinpay.com/mobilepayment/mobile/SaveMchtOrderServlet.action #订单提交
    url_dopickup: http://suyj.ngrok.cc/pay/dopickup #通联支付同步通知
    url_receiveurl: http://suyj.ngrok.cc/pay/receiveurl #通联支付异步通知
    url_orderquery: https://cashier.allinpay.com/gateway/index.do #订单查询（单个）
    url_orderquerybatch: https://cashier.allinpay.com/mchtoq/index.do #订单查询（批量）
    url_refund: https://cashier.allinpay.com/gateway/index.do #退款申请
    url_refundstatus: https://cashier.allinpay.com/mchtoq/refundQuery #退款状态查询

bill:
  defaultAuthenticationType: Integrity
  apiResponseAroundControllerPackagesExecution: "execution(* cn.gotoil.znl.web.controller.api.*.*Action(..))"
  keyOfHashCompareAuthenticationProviderClass: cn.gotoil.znl.classes.HashCompareAuthenticationKeyProvider
  keyOfHashCompareAuthenticationProviderMethod: key
  exceptBodyContentHttpServletRequestWrapperUrls:
    - "/pay/*"
    - "/upload"
    - "/alipay/*"

alipay:
  APPID: 2017041206664290
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoBFNVhMYct5CA3p+zwtZtwBTOlFKVuplgoXre4qhsDz5/ML1H7lqGKzEF6vrXSF/ww7YpqeJnGiwdLJRsGKFIi4I+gRE0ugSqRBBmro2GrGyrt61qlas5Oqf1IFh6YBJ7mGfzTwNE8DMYa7x3IddYJamzRw4aq3IdU+qRe5omwbWvhJrEZYGsmtU8MOwjH8G7JiFo0/HS0U7waGyFfyF7arZfApbwHarTnMOStKA/89ErSx6KkUB6DLUcCZBxyOlHUtsqE93kJwdqKw7EKsMcp2G9fEkRwotyBK+RYhz4PH1N3wzHAg/FEm40I+W5RQu2alwyx9bL8YBb7a6HaiiIwIDAQAB
  RSA_PRIVATE_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3PUyPb5BL7jviin3v/AV3/okmywIzzjNrtM4MIMuAa+/f8Dk+LYDl5rz00OI6TIplanvPrBFjVx7qxbuvu6R683PTtQmUXaKMh5cJJ8PKe4hlo7RtNNgwVBDgmDTvz0rFr8ftzVMBp72QOHmVsKTsntyzDKscTqsHGM2YaMxu+PksWTLDg+YuEXKs0T5WZOuken4yYznSEgpnjJaFvumAqnl/srTgIvGOq8cA9WPLV+V2q+MRYdg/eyH9A76Tu0IgwUxtxVLuLAoTUdA+BNUCFi5rJkUPW55YuY/DdZKlx5RHlfhuwRjxBPjyIZ0qwOXzLjpLKrOMmlcj22b3/p5VAgMBAAECggEAHUVghoU20rpSvKSM65ohsYJqnFTPnEDzO+BdDdjrSS902RwBuOoB7jfGtYDsso1pijvRXWJKQMk4+h3uFmtuIenj9cy0pAu1HKfIO8EraJwFNN9Kwisv4cB8FbSauDgv5JZo5JbpDJmkEXbEDWJzZg0Wik+aweHbNj4DEbaj+ZHsvQa4AalxLggXMqg+I0qu08yjFqnLkyi/BhxxVyK0BmcqHKG51p5Oi7pHQVqtCRdxJoayXfWGw/FlnUkABlpXsinzhR5kYOwhMxffGG0Kfxvs9WCPJa3P55cNrPwKaIQSfrn3mBqZELQMizJgpur9sBKGW/mHwtqOaIJq37VaXQKBgQDm84l2N+R0n5kikS10Ew3hjGZve8DLmczBXz0aJioJq36nfCs0Ukd1hv63EBO9DNpH7Ml0nW62U8aJSZWMhZql6P5i/1MB6geW1mkncmgLeTtTFcG7iB57wb3dleAvI3insuzlIZOjTb+i1UKrkKLlS/OzwUb/HNADsEc7lsE0CwKBgQDLHQWCF9OCGYdFy37+PMQ4RjXH9o7QNGYx2rfqCBZNCbEgV5pq2xOsfsqmp5jYRHUylNGcPNW/HlgNWaXeJdaEGDm2hK02Qbo5AnCKd1f0GpXZLJ3d9YxGkzGoWNLatFol2tqolhFVkoSEa8h5mmtbhQNyTbzIKTX2W1NVtIWTHwKBgQDCiNL5/Dx4K9MOteDmjAI+QUgrkb8lAKjjHTjXpNv2BzmJFGNEECZXDd3SDz3BGWln+kD69H1EIS7zh0Lr+cH5DFfyxYSC8UFxQauTaZ/QQk7BPmtQbmjW76vhURRkQGmqQGGg43Z7sMrB+wbMguljYWWmvR/zVa613K8zt1mIXwKBgF/IAsXzaGlskm7mZK+NhlanPUtbyMMEQsD1zE7Pm3yeumlvBkGnp+JrNDNcy2YI+l9s8F/GDGIA9DLveJmGrF9EcUrRzEDOw/uIW/vgBZj2RH3SXWvDFHBfj0Y9BMnfzLcXOo/PnMMGwfkUPsihekkBM7veTszxKiJPtL+wzmCvAoGBAIA2YcrqdOJs+ZdExVCUre7qy2zigH86ducknOJGZKljrPMA1sClTV4ZF0z4j4T7RTxfOokl9YKXhiEoZLVlLxhijAsj/uze3Zi5/eGryre03TU4HXZ6hL9sxZFVONNtz3QNNjVLDSuAAkjG9MEhv3HmXJdEeZi3OsUTPfJarve/
  notify_url: http://120.25.91.237:8086/alipay/v1/notify_url
  return_url: http://120.25.91.237:8086/alipay/v1/return_url
