server:
  port: 81
  tomcat:
    uri-encoding: UTF-8
  address: 0.0.0.0
  display-name: znl
spring:
  mvc:
    throw-exception-if-no-handler-found: false

  datasource:
      url: jdbc:mysql://201.201.201.173:3306/znl?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true
      username:  developer
      password:  developerDev$$##22

  thymeleaf:
      cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  redis:
    database: 4
    host: 201.201.201.173
    port: 6379
    timeout: 5000
    pool:
      max-active: 64
      max-idle: 8
      max-wait: -1


logging:
  level: debug
  path: logs

management:
  add-application-context-header: false
enableAuth: true

serviceName: "http://183.2.169.57:18089" ## 部署的域名地址，用于 oauth2授权回调


bill:
  defaultAuthenticationType: Signature
  apiResponseAroundControllerPackagesExecution: "execution(* cn.gotoil.nikon.web.controller.api.*.*.*Action(..))"
  keyOfHashCompareAuthenticationProviderClass: cn.gotoil.nikon.classes.HashCompareAuthenticationKeyProvider
  keyOfHashCompareAuthenticationProviderMethod: key
  keyOfHashCompareAuthenticationPathPrefix: "/api"
  exceptBodyContentHttpServletRequestWrapperUrls: "/v1/upload"
  allowDevSkipSignature: "YES" #注意生成环境必须改成NO 删掉也可以的
  ccc:
    url: "http://202.98.60.231:8080/GtTripleGate/NoKeyInServlet"
    copartnerId: 60020021
    copartnerPassword: 361438


